name: 'Install wasi-sdk dependencies'
description: 'Install wasi-sdk dependencies'

runs:
  using: composite
  steps:
    - name: Setup `wasmtime` for tests
      uses: bytecodealliance/actions/wasmtime/setup@v1
      with:
        version: "29.0.1"
    - name: Install ccache, ninja (macOS)
      run: brew install ccache ninja
      if: runner.os == 'macOS'
      shell: bash
    - name: Install ccache, ninja (Windows)
      run: choco install ccache ninja
      if: startsWith(matrix.os, 'windows')
      shell: bash
      # Windows arm runners don't come with rust by default (see https://github.com/actions/partner-runner-images/blob/main/images/arm-windows-11-image.md)
      # but the x86 ones do (see https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md)
    - name: Install cargo (Windows-arm)
      run: choco install rust
      if: matrix.os == 'windows-11-arm'
      shell: bash
    - name: Install ccache, ninja (Linux)
      run: sudo apt-get install -y ccache ninja-build
      if: runner.os == 'Linux'
      shell: bash
